### ISSUE TITLE
agent doesn't work with latest version of TestNG

### ISSUE THREAD

**Issue by Kanaduchi** [reportportal/agent-java-testNG#26] opened 2018-05-07 05:28 UTC
Please update TestNG dependency version to latest. 

Currently with TestNG 6.14.3 after execution I gen an error:
`java.lang.NullPointerException
    at com.epam.reportportal.testng.TestNGService.buildFinishTestMethodRq(TestNGService.java:324)
    at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:155)
    at com.epam.reportportal.testng.BaseTestNGListener.onTestSkipped(BaseTestNGListener.java:103)
    at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:61)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1388)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:633)
    at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
    at org.testng.TestRunner.privateRun(TestRunner.java:648)
    at org.testng.TestRunner.run(TestRunner.java:505)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
    at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
    at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
    at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)`

With version 6.11 there is no such problem

**Comment by evjlobanova** [comment] 2018-05-07 12:38
What version of testNG agent do you use? It is known issue, so in the latest version it should be fixed

**Comment by Kanaduchi** [comment] 2018-05-07 14:00
@evjlobanova With version of TestNG 6.11 there is no such problem. But when I use TestNG 6.14.3 I get such error.

agent-java-testNG I use latest - 4.0.2

**Comment by avarabyeu** [comment] 2018-05-08 09:30
@Kanaduchi unfortunately, i cannot reproduce it. 
Could you please fork https://github.com/reportportal/example-java-TestNG/tree/master/logback and give us some example so we can reproduce and fix

**Comment by evjlobanova** [comment] 2018-05-11 09:09
@Kanaduchi ^

**Comment by evjlobanova** [comment] 2018-07-16 11:19
@Kanaduchi is it still actual question?

**Comment by Kanaduchi** [comment] 2018-07-17 09:35
Yes, problem is still actual. 

If I'm not mistaken my problem is duplicated by https://github.com/reportportal/agent-java-testNG/issues/27. So I'm waiting for resolving this issue

**Comment by avarabyeu** [comment] 2018-07-23 10:55
#27 describes another issue. Closing this one in favor of #27 since the current one (with NPE cannot be reproduced). Feel free to re-open if issue still relevant

**Closed by avarabyeu** 2018-07-23 10:55 UTC
